config/routes.rb
Rails.application.routes.draw do
  resources :customers, except: [:create, :new, :destroy] do
    post :do_white, on: :member
    post :do_black, on: :member
  end

  root to: 'customers#index'

  get 'blacklist', to: 'customers#blacklist'
  get '/search', to: 'customers#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, format: { with: /\A(([0-9][\- ]{1}|\+7[\- ]?|\+\d{3}|)[\- ]?)?(\(?\d{1,8}\)?[\- ]?)?[\d\- ]{5,10}\Z/, message: "phone format +7 916 1113344" }

  validates :phone, uniqueness: true

  scope :available, -> { where(blacklisted: false) }
  scope :blocked, -> { where(blacklisted: true) }

  def to_blacklist!
    update!(blacklisted: true)
  end

  def blacklist_off!
    update!(blacklisted: true)
  end

  def black?
    blacklisted
  end

  def self.search(phone)
    available.where(phone: phone.strip).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, except: %i[index blacklist search]

  def index
    @customers = Customer.available
  end

  def edit; end

  def update
    if @customer.update(customer_params)   
      redirect_to root_path, notice: 'Клиент успешно обновлён!'
    else
      render :edit
    end
  end

  def do_black
    @customer.to_blacklist!

    redirect_to root_path
  end

  def do_white
    @customer.blacklist_off!

    redirect_to blacklist_path
  end

  def blacklist
    @black_customers = Customer.blocked
  end

  def search
    if phone.blank?
      redirect_to(blacklist_path, alert: "Поле для поиска не заполнено!")
    elsif customer_by_phone.blank?
      redirect_to(blacklist_path, alert: "Клиент не найден!")
    else
      customer_by_phone.update!(blacklisted: true)
      redirect_to(blacklist_path, alert: "Клиент успешно добавлен в чёрный список!")
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end


  def customer_params
    params.require(:customer).permit(:name, :phone,
                                     :description, :blacklisted)
  end

  def customer_by_phone
    Customer.search(phone)
  end

  def phone
    params[:phone]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_customer.html.erb
<tr>
  <td><%= customer.name %></td>
  <td><%= customer.phone %></td>
  <td><%= customer.description %></td>
  <td>
    <%= link_to content_tag('span', 'Edit customer', class: 'btn btn-primary'), edit_customer_path(customer), class: 'action' %>
  </td>
  <td>
    <% if customer.black? %>
      <%= link_to 'Drop from black',
            do_white_customer_path(customer),
            method: :post,
            class: 'btn btn-success'
      %>
    <% else %>
      <%= link_to 'To blacklist',
            do_black_customer_path(customer),
            method: :post,
            class: 'btn btn-danger'
      %>
    <% end %>
  </td>
</tr>

app/views/customers/_form.html.erb
<div class="col-md-8">
  <%= simple_form_for(@customer) do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: @customer} %>

    <div class="container">
      <div class="row">
        <div class="form-group col-xs-4">
          <p><%= f.label :name, 'Название', class: 'form-label' %></p>
          <p><%= f.text_field :name, class: 'form-control', required: true %></p>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-xs-4">
          <p><%= f.label :phone, 'Описаниe', class: 'form-label' %></p>
          <p><%= f.text_field :phone, class: 'form-control', required: true %></p>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-xs-4">
          <p><%= f.label :description, 'Описаниe', class: 'form-label' %></p>
          <p><%= f.text_field :description, class: 'form-control', required: true %></p>
        </div>
      </div>

      <div class="form-group col-auto my-1">
        <div class="custom-control custom-checkbox mr-sm-2">
          <div class="field">
            <%= f.input :blacklisted %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-xs-4">
          <p><%= f.submit 'Save', class: 'btn btn-info' %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/customers/blacklist.html.erb
<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="text-center">
  <h2>Members of Blacklist</h2>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 mb-3">
      <%= form_for '', url: search_path, role: 'search', html: { class: 'form-inline' },
            method: :get do %>
        <%= text_field_tag :phone,
              params[:phone],
              placeholder: "Enter phone",
              class: 'form-control'
        %>
        <%= button_tag 'Add to blacklist', name: nil, class: 'btn btn-primary ml-3' %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class=col-md-8>
      <div class="buffer-top">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Description</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
            <%= render partial: 'customers/customer', collection: @black_customers %>
          </tbody>
        </table>
      </div>
    </div>

    <div class=col-md-4>
      <div class="buffer-top">
        <%= link_to 'To the Main Page', root_path, class: 'btn btn-link' %>
      </div>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<div>
  <h3>Editing Customer</h3>
  <%= render 'form', customer: @customer %>
</div>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<center><h2>Clients</h2></center>

<div class="container">
  <div class="row">
    <div class=col-md-10>
      <div class="buffer-top">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Description</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
            <%= render partial: 'customers/customer', collection: @customers %>
          </tbody>
          </table>
      </div>
    </div>

    <div class=col-md-2>
      <div class="buffer-top">
        <%= link_to 'To the Blacklist', blacklist_path, class: 'btn btn-link' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blacklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>

<% if errors.any? %>
  <div class="alert alert-danger">
    <div class="lead buffer-bottom">
      В вашей форме <%#= t 'errors', count: errors.count %>
    </div>
    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>